config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:new, :create, :show] do
    resources :registered_applications
  end

  resources :registered_applications, only: [] do
    resources :events, only: [:create, :destroy]
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  get 'welcome/index'

  get 'welcome/about'

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ApplicationRecord
  belongs_to :user
  has_many :events, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :registered_applications
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  skip_before_action :authenticate_user!, only: [:create]
  before_action :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def preflight
    head 200
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application
      @event = registered_application.events.new(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    else
      render json: {errors: "Unregistered application"}, status: :unprocessable_entity
    end
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_apps = RegisteredApplication.all
  end

  def show
    @registered_app = RegisteredApplication.find(params[:id])
    @events = @registered_app.events.group_by(&:name)
  end

  def new
    @registered_app = RegisteredApplication.new
  end

  def create
    @registered_app = RegisteredApplication.new(app_params)
    @registered_app.user = current_user

    if @registered_app.save
      flash[:notice] = "App was saved."
      redirect_to [current_user, @registered_app]
    else
      flash.now[:alert] = "There was an error saving the app. Please try again."
      render :new
    end
  end

  def edit
    @registered_app = RegisteredApplication.find(params[:id])
  end

  def update
    @registered_app = RegisteredApplication.find(params[:id])
    @registered_app.assign_attributes(app_params)

    if @registered_app.save
      flash[:notice] = "App was updated."
      redirect_to [current_user, @registered_app]
    else
      flash.now[:alert] = "There was an error saving the app. Please try again."
      render :edit
    end
  end

  def destroy
    @registered_app = RegisteredApplication.find(params[:id])

    if @registered_app.destroy
      flash[:notice] = "\"#{@registered_app.name}\" was deleted successfully."
      redirect_to user_registered_applications_path
    else
      flash.now[:alert] = "There was an error deleting the app."
      render :show
    end
  end

  private
  def app_params
    params.require(:registered_application).permit(:name, :url)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @registered_apps = @user.registered_applications
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, except: [:index, :about]
  
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Scrutinize
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{href: "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css", rel: "stylesheet", integrity: "sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN", crossorigin: "anonymous"}
  %body
    .container
      %ul.nav.nav-pills
        %li.active= link_to "Scrutinize", welcome_index_path
        %li= link_to "About", welcome_about_path
        - if user_signed_in?
          %li= link_to "My Apps", user_registered_applications_path(current_user)
        .pull-right.user-info
          - if user_signed_in?
            Signed in as:
            %strong= current_user.email
            |
            \#{link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'} - #{link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'}
          - else
            = link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'
            \-
            \#{link_to "Sign In", new_user_session_path, :class => 'navbar-link'}
    - if flash[:notice]
      .alert.alert-success
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:notice]
    - elsif flash.now[:alert]
      .alert.alert-danger
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash.now[:alert]
    - elsif flash[:alert]
      .alert.alert-warning
        %button.close{"data-dismiss" => "alert", :type => "button"} ×
        = flash[:alert]
    .container
      = yield

app/views/registered_applications/_form.html.haml
.col-md-8
  = form_for [user, registered_app] do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control', placeholder: "Enter app name"
    .form-group
      = f.label :url
      = f.text_field :url, class: 'form-control', placeholder: "Enter app url"
    .form-group
      = f.submit "Save", class: 'btn btn-success'

app/views/registered_applications/_registered_app.html.haml
.row
  .col-md-8
    %h3
      = link_to registered_application.name, user_registered_application_path(registered_application.user.id, registered_application.id)
      %br/
      = registered_application.url

app/views/registered_applications/edit.html.haml
%h2 Edit App
= render partial: 'form', locals: { user: current_user, registered_app: @registered_app }

app/views/registered_applications/index.html.haml
%h2
  Registered Apps for #{current_user.email}
.row
  .col-md-8
    .media
      .media-body
        - current_user.registered_applications.each do |app|
          = render 'registered_applications/registered_app', registered_application: app
        = link_to "Register New App", new_user_registered_application_path, class: 'btn btn-info'

app/views/registered_applications/new.html.haml
%h2 New App
= render partial: 'form', locals: { user: current_user, registered_app: @registered_app }

app/views/registered_applications/show.html.haml
.row
  .col-md-4
    %h2= @registered_app.name
    %h4= @registered_app.url
    = link_to "Edit App", edit_user_registered_application_path(current_user, @registered_app), class: 'btn btn-success'
    = link_to "Delete App", [current_user, @registered_app], method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this app?'}
.row
  .col-md-12
    = pie_chart @registered_app.events.group(:name).count
    = line_chart @registered_app.events.group_by_day(:created_at).count
.row
  .col-md-12
    %h3 Events Log:
    - @registered_app.events.each do |event|
      %p
        = event.name
        \: #{event.created_at}

app/views/welcome/about.html.haml
.well
  %h3 Scrutinize is an analytics service to track events on websites.
  %h4 Features:
  %ul
    %li A client-side JavaScript snippet that allows a user to track events on their website.
    %li A server-side API that captures and saves those events to a database.
    %li A Rails 5 application that displays the captured event data for a user.
  %h5
    %a{:href => "https://github.com/lkang-pdx/scrutinize"} GitHub Repo

app/views/welcome/index.html.haml
#banner
  .banner_content
    %h1 Real Time Analytics
    %p
      = link_to "Get Started", new_user_registration_path, class: "btn btn-primary btn-md"
%section.selling-points.container.clearfix
  .point.column.third
    %i.fa.fa-database.fa-3x
    %h5.point-title Data
    %p.point-description Clicks, form submissions, page views in one place.
  .point.column.third
    %i.fa.fa-info-circle.fa-3x
    %h5.point-title Information
    %p.point-description Define events and organize the building blocks of your analysis.
  .point.column.third
    %i.fa.fa-area-chart.fa-3x
    %h5.point-title Insights
    %p.point-description Uncover insights that you'll actually take action on.